name: Test-Workflow-CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, ManagedDevOpsPool-WE]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: powershell
        shell : pwsh
        run: |
          Write-Host "Hello World"

